M48
; DRILL file {KiCad 8.0.8} date 2025-01-20T22:43:25+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-01-20T22:43:25+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.120
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.500
%
G90
G05
T1
X148.2Y-135.3
T2
X159.2Y-135.3
T3
X118.25Y-103.25
X118.5Y-138.75
X164.4Y-103.1
X164.4Y-138.9
M30
