M48
; DRILL file KiCad 10.0.1 date 2026-05-02T18:28:22
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-02T18:28:22-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X115.5Y-120.5
X115.5Y-127.5
T2
X74.0Y-104.0
X74.596Y-125.404
X124.672Y-124.672
X125.0Y-104.0
M30
